### ISSUE TITLE
charlote not esxyt

### ISSUE THREAD

**Issue by PringlePot** [c-harlotte/yaycat#8]
GRR

**Comment by deathawp** [comment]
Lol pringle s mad

**Comment by f7nl4y** [comment]
discord.gg/img
IMGS.BAR BEST IMAGE HOST ( not cuz astral fork but cuz owners )

**Comment by deathawp** [comment]
No one care

**Comment by deathawp** [comment]
![image](https://user-images.githubusercontent.com/75097279/123012417-33a2f100-d390-11eb-832c-182fca47e8b2.png)

**Comment by deathawp** [comment]
Lol

**Comment by deathawp** [comment]
Poopa host quack host go quack quack 🦆

**Comment by deathawp** [comment]
🖕 🖕 🖕 🖕 🖕

**Comment by c-harlotte** [comment]
can you shut the FUCK UP i get an email every time you reply to this GO DIE
